version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

volumes:
  redis-data:

networks:
  redis-network:
    driver: bridge

